2020-06-10 19:59:37 jdbc[3]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:923)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:988)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 15 more
2020-06-10 19:59:37 jdbc[3]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:923)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:988)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 15 more
2020-06-10 20:07:26 database: wrong user or password; user: ""
org.h2.message.DbException: Nombre de usuario ó password incorrecto
Wrong user name or password [28000-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Engine.openSession(Engine.java:131)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:923)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:988)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Nombre de usuario ó password incorrecto
Wrong user name or password [28000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:461)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 20 more
2020-06-10 20:08:01 jdbc[5]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:923)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:988)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:923)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:988)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 15 more
2020-06-10 20:09:46 jdbc[6]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "CREATE TABLE  EASYCOFFEBD.FINCA (
  FIN_IDFINCA INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1,[*] INCREMENT BY 1),
  FIN_NOMBREFINCA VARCHAR(45) NOT NULL,
  PRIMARY KEY (FIN_IDFINCA))"; se esperaba "[, ::, AT, FORMAT, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, START, INCREMENT, MINVALUE, NOMINVALUE, MAXVALUE, NOMAXVALUE, CYCLE, NOCYCLE, NO, CACHE, NOCACHE, )"
Syntax error in SQL statement "CREATE TABLE  EASYCOFFEBD.FINCA (
  FIN_IDFINCA INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1,[*] INCREMENT BY 1),
  FIN_NOMBREFINCA VARCHAR(45) NOT NULL,
  PRIMARY KEY (FIN_IDFINCA))"; expected "[, ::, AT, FORMAT, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, START, INCREMENT, MINVALUE, NOMINVALUE, MAXVALUE, NOMAXVALUE, CYCLE, NOCYCLE, NO, CACHE, NOCACHE, )"; SQL statement:
CREATE TABLE  easycoffebd.Finca (
  fin_idFinca INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  fin_nombreFinca VARCHAR(45) NOT NULL,
  PRIMARY KEY (fin_idFinca)) [42001-200]
2020-06-10 20:19:36 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at DAO.DAOManager.<init>(DAOManager.java:29)
	at DAO.DAOManager.main(DAOManager.java:107)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 20 more
2020-06-10 20:20:28 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at DAO.DAOManager.<init>(DAOManager.java:29)
	at DAO.DAOManager.main(DAOManager.java:107)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 20 more
2020-06-10 20:24:49 jdbc[7]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:923)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:988)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:923)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:988)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 15 more
2020-06-10 20:27:47 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Nombre de columna ambigua "PER_CEDULACIUDADANIA"
Ambiguous column name "PER_CEDULACIUDADANIA"; SQL statement:
SELECT * FROM EASYCOFFEBD.PERSONA NATURAL JOIN EASYCOFFEBD.USUARIO WHERE PER_CEDULACIUDADANIA = ? [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.expression.condition.Comparison.mapColumns(Comparison.java:505)
	at org.h2.expression.condition.ConditionAndOr.mapColumns(ConditionAndOr.java:260)
	at org.h2.command.dml.Select.mapColumns(Select.java:1603)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at DAO.UsuarioDAO.obtener(UsuarioDAO.java:170)
	at Control.ControlUsuarios.verificarExistenciaCedula(ControlUsuarios.java:46)
	at Control.ControlUsuarios.verificarLogin(ControlUsuarios.java:66)
	at PruebasPrimerNivel.IngresarAplicacion.ingresarAlSistema(IngresarAplicacion.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
2020-06-10 20:27:47 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Nombre de columna ambigua "PER_CEDULACIUDADANIA"
Ambiguous column name "PER_CEDULACIUDADANIA"; SQL statement:
SELECT * FROM EASYCOFFEBD.PERSONA NATURAL JOIN EASYCOFFEBD.USUARIO WHERE PER_CEDULACIUDADANIA = ? [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.expression.condition.Comparison.mapColumns(Comparison.java:505)
	at org.h2.expression.condition.ConditionAndOr.mapColumns(ConditionAndOr.java:260)
	at org.h2.command.dml.Select.mapColumns(Select.java:1603)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at DAO.UsuarioDAO.obtener(UsuarioDAO.java:170)
	at Control.ControlUsuarios.verificarExistenciaCedula(ControlUsuarios.java:46)
	at PruebasPrimerNivel.IngresarAplicacion.existenciaUsuario(IngresarAplicacion.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
2020-06-10 20:29:37 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at DAO.DAOManager.<init>(DAOManager.java:28)
	at Control.InicializarSistema.<init>(InicializarSistema.java:26)
	at Frontera.FramePrincipal.<clinit>(FramePrincipal.java:32)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 27 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 21 more
2020-06-10 20:29:58 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at DAO.DAOManager.<init>(DAOManager.java:28)
	at PruebasPrimerNivel.IngresarAplicacion.<clinit>(IngresarAplicacion.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 48 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 42 more
2020-06-10 20:30:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
INSERT INTO USUARIO VALUES (?, ?) [42102-200]
2020-06-10 20:30:20 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Nombre de columna ambigua "PER_CEDULACIUDADANIA"
Ambiguous column name "PER_CEDULACIUDADANIA"; SQL statement:
SELECT * FROM EASYCOFFEBD.PERSONA NATURAL JOIN EASYCOFFEBD.USUARIO WHERE PER_CEDULACIUDADANIA = ? [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.expression.condition.Comparison.mapColumns(Comparison.java:505)
	at org.h2.expression.condition.ConditionAndOr.mapColumns(ConditionAndOr.java:260)
	at org.h2.command.dml.Select.mapColumns(Select.java:1603)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at DAO.UsuarioDAO.obtener(UsuarioDAO.java:170)
	at Control.ControlUsuarios.verificarExistenciaCedula(ControlUsuarios.java:46)
	at Control.ControlUsuarios.verificarLogin(ControlUsuarios.java:66)
	at PruebasPrimerNivel.IngresarAplicacion.ingresarAlSistema(IngresarAplicacion.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
2020-06-10 20:30:20 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Nombre de columna ambigua "PER_CEDULACIUDADANIA"
Ambiguous column name "PER_CEDULACIUDADANIA"; SQL statement:
SELECT * FROM EASYCOFFEBD.PERSONA NATURAL JOIN EASYCOFFEBD.USUARIO WHERE PER_CEDULACIUDADANIA = ? [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.expression.condition.Comparison.mapColumns(Comparison.java:505)
	at org.h2.expression.condition.ConditionAndOr.mapColumns(ConditionAndOr.java:260)
	at org.h2.command.dml.Select.mapColumns(Select.java:1603)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at DAO.UsuarioDAO.obtener(UsuarioDAO.java:170)
	at Control.ControlUsuarios.verificarExistenciaCedula(ControlUsuarios.java:46)
	at PruebasPrimerNivel.IngresarAplicacion.existenciaUsuario(IngresarAplicacion.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:30:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIO" no encontrada
Table "USUARIO" not found; SQL statement:
DELETE FROM USUARIO WHERE PER_CEDULACIUDADANIA = ? [42102-200]
2020-06-10 20:31:51 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Nombre de columna ambigua "PER_CEDULACIUDADANIA"
Ambiguous column name "PER_CEDULACIUDADANIA"; SQL statement:
SELECT * FROM EASYCOFFEBD.PERSONA NATURAL JOIN EASYCOFFEBD.USUARIO WHERE PER_CEDULACIUDADANIA = ? [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.expression.condition.Comparison.mapColumns(Comparison.java:505)
	at org.h2.expression.condition.ConditionAndOr.mapColumns(ConditionAndOr.java:260)
	at org.h2.command.dml.Select.mapColumns(Select.java:1603)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at DAO.UsuarioDAO.obtener(UsuarioDAO.java:170)
	at Control.ControlUsuarios.verificarExistenciaCedula(ControlUsuarios.java:46)
	at Control.ControlUsuarios.verificarLogin(ControlUsuarios.java:66)
	at PruebasPrimerNivel.IngresarAplicacion.ingresarAlSistema(IngresarAplicacion.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
2020-06-10 20:31:51 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Nombre de columna ambigua "PER_CEDULACIUDADANIA"
Ambiguous column name "PER_CEDULACIUDADANIA"; SQL statement:
SELECT * FROM EASYCOFFEBD.PERSONA NATURAL JOIN EASYCOFFEBD.USUARIO WHERE PER_CEDULACIUDADANIA = ? [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.expression.condition.Comparison.mapColumns(Comparison.java:505)
	at org.h2.expression.condition.ConditionAndOr.mapColumns(ConditionAndOr.java:260)
	at org.h2.command.dml.Select.mapColumns(Select.java:1603)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at DAO.UsuarioDAO.obtener(UsuarioDAO.java:170)
	at Control.ControlUsuarios.verificarExistenciaCedula(ControlUsuarios.java:46)
	at PruebasPrimerNivel.IngresarAplicacion.existenciaUsuario(IngresarAplicacion.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
2020-06-10 20:32:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Nombre de columna ambigua "PER_CEDULACIUDADANIA"
Ambiguous column name "PER_CEDULACIUDADANIA"; SQL statement:
SELECT * FROM EASYCOFFEBD.PERSONA NATURAL JOIN EASYCOFFEBD.USUARIO WHERE PER_CEDULACIUDADANIA = 1 [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.expression.condition.Comparison.mapColumns(Comparison.java:505)
	at org.h2.expression.condition.ConditionAndOr.mapColumns(ConditionAndOr.java:260)
	at org.h2.command.dml.Select.mapColumns(Select.java:1603)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatementForExtraction(SQLExecutionHelper.java:856)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:86)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:149)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
2020-06-10 20:33:55 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Nombre de columna ambigua "PER_CEDULACIUDADANIA"
Ambiguous column name "PER_CEDULACIUDADANIA"; SQL statement:
SELECT * FROM EASYCOFFEBD.PERSONA NATURAL JOIN EASYCOFFEBD.USUARIO WHERE PER_CEDULACIUDADANIA = ? [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.expression.condition.Comparison.mapColumns(Comparison.java:505)
	at org.h2.expression.condition.ConditionAndOr.mapColumns(ConditionAndOr.java:260)
	at org.h2.command.dml.Select.mapColumns(Select.java:1603)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at DAO.UsuarioDAO.obtener(UsuarioDAO.java:170)
	at Control.ControlUsuarios.verificarExistenciaCedula(ControlUsuarios.java:46)
	at Control.ControlUsuarios.verificarLogin(ControlUsuarios.java:66)
	at PruebasPrimerNivel.IngresarAplicacion.ingresarAlSistema(IngresarAplicacion.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
2020-06-10 20:33:55 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Nombre de columna ambigua "PER_CEDULACIUDADANIA"
Ambiguous column name "PER_CEDULACIUDADANIA"; SQL statement:
SELECT * FROM EASYCOFFEBD.PERSONA NATURAL JOIN EASYCOFFEBD.USUARIO WHERE PER_CEDULACIUDADANIA = ? [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.expression.condition.Comparison.mapColumns(Comparison.java:505)
	at org.h2.expression.condition.ConditionAndOr.mapColumns(ConditionAndOr.java:260)
	at org.h2.command.dml.Select.mapColumns(Select.java:1603)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
	at DAO.UsuarioDAO.obtener(UsuarioDAO.java:170)
	at Control.ControlUsuarios.verificarExistenciaCedula(ControlUsuarios.java:46)
	at PruebasPrimerNivel.IngresarAplicacion.existenciaUsuario(IngresarAplicacion.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
2020-06-10 20:35:16 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at DAO.DAOManager.<init>(DAOManager.java:28)
	at PruebasPrimerNivel.RecuperarContrasena.<clinit>(RecuperarContrasena.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 48 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Camilo Vargas/Documents/NetBeansProjects/EasyCoffee/dbtest.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 42 more
2020-06-10 20:35:37 jdbc[91]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at DAO.DAOManager.<init>(DAOManager.java:28)
	at Control.ControlUsuarios.<init>(ControlUsuarios.java:17)
	at PruebasPrimerNivel.RecuperarContrasena.RecuperarContraseña(RecuperarContrasena.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 45 more
